services:
  - type: web
    name: couchdb
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: COUCHDB_USER
        value:admin
      - key: COUCHDB_PASSWORD
        value:admin123
